./lem-in < map/bug1.map
./lem-in < map/bug2.map
./lem-in < map/bug3.map
./lem-in < map/bug4.map
./lem-in < map/bug5.map
./lem-in < map/bug6.map
./lem-in < map/bug7.map
./lem-in < map/bug8.map
./lem-in < map/bug9.map
./lem-in < map/bug10.map
./lem-in < map/bug11.map
./lem-in < map/bug12.map
./lem-in < map/bug13.map
./lem-in < map/bug13.map
./lem-in < map/error.map
./lem-in < map/error2.map
./lem-in < map/error3.map
./lem-in < map/error4.map
./lem-in < map/error5.map
./lem-in < map/error6.map
./lem-in < map/error7.map
./lem-in < map/error8.map
./lem-in < map/error9.map
./lem-in < map/error10.map
./lem-in < map/error11.map
./lem-in < map/error12.map
./lem-in < map/error13.map
./lem-in < map/error13.map
./lem-in < map/error14.map
